"""
Configuration dictionaries for range_vol_am market scanning.

This module contains all the configuration data structures used in the market scanning
reports including ticker definitions, spreads, options, physical spots, and asset classifications.
"""

fom_keys = [
    "RISK",
    "EQT",
    "FI",
    "CCY",
    "VOL",
    "PM",
    "BRT",
    "WTI",
    "DIST",
    "GASOLINE",
    "GAS",
    "HH",
    "TTF",
    "BM",
    "Bulks",
    "GR",
    "SFT",
]

name_dict = {
    "ESA Index": ("EQT", "TICKER", "FLAT", 1, 1),
    "NQA Index": ("EQT", "TICKER", "FLAT", 1, 1),
    "RTYA Index": ("EQT", "TICKER", "FLAT", 1, 1),
    "GXA Index": ("EQT", "TICKER", "FLAT", 1, 1),
    "VGA Index": ("EQT", "TICKER", "FLAT", 1, 1),
    "NKA Index": ("EQT", "TICKER", "FLAT", 1, 1),
    "MESA Index": ("EQT", "TICKER", "FLAT", 1, 1),
    "IFBA Index": ("EQT", "TICKER", "FLAT", 1, 1),
    "XUA Index": ("EQT", "TICKER", "FLAT", 1, 1),
    "MSZZCYDE Index": ("EQT", "TICKER", "FLAT", 1, 0),
    "MSEECYDE Index": ("EQT", "TICKER", "FLAT", 1, 0),
    "UXA Index": ("EQT", "TICKER", "FLAT", 1, 1),
    "MSZZMOMO Index": ("EQT", "TICKER", "FLAT", 1, 0),
    "KWEB US Equity": ("EQT", "TICKER", "FLAT", 1, 1),
    "ECA Curncy": ("CCY", "TICKER", "FLAT", 1, 1),
    "ADA Curncy": ("CCY", "TICKER", "FLAT", 1, 1),
    "JYA Curncy": ("CCY", "TICKER", "FLAT", 1, 1),
    "CDA Curncy": ("CCY", "TICKER", "FLAT", 1, 1),
    "DXA Curncy": ("CCY", "TICKER", "FLAT", 1, 1),
    "USDCNH Curncy": ("CCY", "COPY", "FLAT", 1, 0),
    "USDINR Curncy": ("CCY", "COPY", "FLAT", 1, 0),
    "USDBRL Curncy": ("CCY", "COPY", "FLAT", 1, 0),
    "USDRUB Curncy": ("CCY", "COPY", "FLAT", 0, 0),
    "FXJPEMCS Index": ("CCY", "COPY", "FLAT", 1, 0),
    "BTCA Curncy": ("CCY", "TICKER", "FLAT", 1, 1),
    "DCRA Curncy": ("CCY", "TICKER", "FLAT", 1, 1),
    "TUA Comdty": ("FI", "TICKER", "FLAT", 1, 1),
    "TYA Comdty": ("FI", "TICKER", "FLAT", 1, 1),
    "RXA Comdty": ("FI", "TICKER", "FLAT", 1, 1),
    "USGG2YR Index": ("FI", "COPY", "SPRD", 1, 0),
    "USGG5YR Index": ("FI", "COPY", "SPRD", 1, 0),
    "USGG10YR Index": ("FI", "COPY", "SPRD", 1, 0),
    "USGG5Y5Y Index": ("FI", "COPY", "SPRD", 1, 0),
    "USYC2Y10 Index": ("FI", "COPY", "SPRD", 1, 0),
    "USYC5Y30 Index": ("FI", "COPY", "SPRD", 1, 0),
    "USSWIT1 Curncy": ("FI", "COPY", "SPRD", 1, 0),
    "USSWIT2 Curncy": ("FI", "COPY", "SPRD", 1, 0),
    "USSWIT5 Curncy": ("FI", "COPY", "SPRD", 1, 0),
    "USSWIT10 Curncy": ("FI", "COPY", "SPRD", 1, 0),
    "FWISUS55 Index": ("FI", "COPY", "SPRD", 1, 0),
    ".USGGT1 Index": ("FI", "COPY", "SPRD", 1, 0),
    ".USGGT2 Index": ("FI", "COPY", "SPRD", 1, 0),
    ".USGGT5 Index": ("FI", "COPY", "SPRD", 1, 0),
    ".USGGT10 Index": ("FI", "COPY", "SPRD", 1, 0),
    "SFRA Comdty": ("FI", "TICKER", "FLAT", 1, 1),
    "SFR2 Comdty": ("FI", "CONTRACT", "FLAT", 1, 1),
    "SFR3 Comdty": ("FI", "CONTRACT", "FLAT", 1, 1),
    "SFR4 Comdty": ("FI", "CONTRACT", "FLAT", 1, 1),
    "GCA Comdty": ("PM", "TICKER", "FLAT", 1, 1),
    "SIA Comdty": ("PM", "TICKER", "FLAT", 1, 1),
    "PLA Comdty": ("PM", "TICKER", "FLAT", 1, 1),
    "PAA Comdty": ("PM", "TICKER", "FLAT", 1, 1),
    "GC 3M 100 VOL BVOL Comdty": ("PM", "COPY", "SPRD", 1, 0),
    "XAUUSD25R3M BGN Curncy": ("PM", "COPY", "SPRD", 1, 0),
    "AUAA Comdty": ("PM", "TICKER", "FLAT", 1, 1),
    "SAIA Comdty": ("PM", "TICKER", "FLAT", 1, 1),
    "GDX US Equity": ("PM", "COPY", "FLAT", 1, 1),
    "GDXJ US Equity": ("PM", "COPY", "FLAT", 1, 1),
    "COA Comdty": ("BRT", "TICKER", "FLAT", 1, 1),
    "CO2 Comdty": ("BRT", "CONTRACT", "FLAT", 1, 1),
    "CO3 Comdty": ("BRT", "CONTRACT", "FLAT", 1, 1),
    "CO4 Comdty": ("BRT", "CONTRACT", "FLAT", 0, 1),
    "CO6 Comdty": ("BRT", "CONTRACT", "FLAT", 0, 1),
    "CO12 Comdty": ("BRT", "CONTRACT", "FLAT", 0, 1),
    "CODEC1 Comdty": ("BRT", "FUT_CUR_GEN_TICKER", "FLAT", 1, 1),
    "CODEC2 Comdty": ("BRT", "FUT_CUR_GEN_TICKER", "FLAT", 1, 1),
    "COJUN1 Comdty": ("BRT", "FUT_CUR_GEN_TICKER", "FLAT", 0, 1),
    "S:COCO 2-6 Comdty": ("BRT", "CALSPRD", "SPRD", 1, 1),
    "CO 1st Spread": ("BRT", "CALCULATE", "SPRD", 1, 1),
    "CO 2nd Spread": ("BRT", "CALCULATE", "SPRD", 1, 1),
    "CO 3rd Spread": ("BRT", "CALCULATE", "SPRD", 1, 1),
    "CO Jun-Dec Spread": ("BRT", "CALCULATE", "SPRD", 1, 1),
    "CO Dec-Dec Spread": ("BRT", "CALCULATE", "SPRD", 1, 1),
    "CO 1M 100 VOL BVOL Comdty": ("BRT", "COPY", "SPRD", 1, 0),
    ".CO1MRR Index": ("BRT", "COPY", "SPRD", 1, 0),
    "SXEP Index": ("BRT", "COPY", "FLAT", 1, 0),
    "BWCHEM Index": ("BRT", "COPY", "FLAT", 1, 0),
    "SABIC AB Equity": ("BRT", "COPY", "FLAT", 1, 1),
    "SH000908 Index": ("BRT", "COPY", "FLAT", 1, 0),
    "DATA Comdty": ("BRT", "TICKER", "FLAT", 0, 1),
    "DAT2 Comdty": ("BRT", "CONTRACT", "FLAT", 1, 1),
    "DAT3 Comdty": ("BRT", "CONTRACT", "FLAT", 1, 1),
    "DAT4 Comdty": ("BRT", "CONTRACT", "FLAT", 1, 1),
    "DAT 1st Spread": ("BRT", "CALCULATE", "SPRD", 0, 1),
    "DAT 2nd Spread": ("BRT", "CALCULATE", "SPRD", 1, 1),
    "DAT 3rd Spread": ("BRT", "CALCULATE", "SPRD", 1, 1),
    "FDBSM1 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FDBSM2 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FDBSM3 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FNNSQ 1Q1 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FNOSQ 1Q1 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FSQCQ 1Q1 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FWJSQ 1Q1 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FROSQ 1Q1 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FDBDM1 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FDBDM2 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FDBDM3 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FDUSM1 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FDUSM2 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FDUSQ 1Q1 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "MUCDAT Comdty": ("BRT", "COPY", "SPRD", 1, 0),
    "MUCDAT 2 Comdty": ("BRT", "OILSPRD", "SPRD", 1, 0),
    "MUCDAT 3 Comdty": ("BRT", "OILSPRD", "SPRD", 1, 0),
    "HWTCO Comdty": ("BRT", "COPY", "SPRD", 1, 0),
    "FJWHM1 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FJWHM2 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FSMCM1 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FSMCM2 Index": ("BRT", "COPY", "SPRD", 1, 0),
    "FSCDM1 Index": ("GASOLINE", "COPY", "SPRD", 1, 0),
    "FSCDM2 Index": ("GASOLINE", "COPY", "SPRD", 1, 0),
    "FSNOM1 Index": ("GASOLINE", "COPY", "SPRD", 1, 0),
    "FSNOM2 Index": ("GASOLINE", "COPY", "SPRD", 1, 0),
    "FSGAM1 Index": ("GASOLINE", "COPY", "SPRD", 1, 0),
    "FSGAM2 Index": ("GASOLINE", "COPY", "SPRD", 1, 0),
    "FSGCM1 Index": ("DIST", "COPY", "SPRD", 1, 0),
    "FSGCM2 Index": ("DIST", "COPY", "SPRD", 1, 0),
    "FSEUM1 Index": ("DIST", "COPY", "SPRD", 1, 0),
    "FSEUM2 Index": ("DIST", "COPY", "SPRD", 1, 0),
    "FSG1M1 Index": ("DIST", "COPY", "SPRD", 1, 0),
    "FSG1M2 Index": ("DIST", "COPY", "SPRD", 1, 0),
    "CLA Comdty": ("WTI", "TICKER", "FLAT", 1, 1),
    "CL2 Comdty": ("WTI", "CONTRACT", "FLAT", 1, 1),
    "CL3 Comdty": ("WTI", "CONTRACT", "FLAT", 1, 1),
    "CL4 Comdty": ("WTI", "CONTRACT", "FLAT", 0, 1),
    "CL6 Comdty": ("WTI", "CONTRACT", "FLAT", 0, 1),
    "CLDEC1 Comdty": ("WTI", "FUT_CUR_GEN_TICKER", "FLAT", 1, 1),
    "CLDEC2 Comdty": ("WTI", "FUT_CUR_GEN_TICKER", "FLAT", 1, 1),
    "CLJUN1 Comdty": ("WTI", "FUT_CUR_GEN_TICKER", "FLAT", 0, 1),
    "S:CLCL 2-6 Comdty": ("WTI", "CALSPRD", "SPRD", 1, 1),
    "CL 1st Spread": ("WTI", "CALCULATE", "SPRD", 1, 1),
    "CL 2nd Spread": ("WTI", "CALCULATE", "SPRD", 1, 1),
    "CL 3rd Spread": ("WTI", "CALCULATE", "SPRD", 1, 1),
    "CL Jun-Dec Spread": ("WTI", "CALCULATE", "SPRD", 1, 1),
    "CL Dec-Dec Spread": ("WTI", "CALCULATE", "SPRD", 1, 1),
    "CL 1M 100 VOL BVOL Comdty": ("WTI", "COPY", "SPRD", 1, 0),
    ".CL1MRR Index": ("WTI", "COPY", "SPRD", 1, 0),
    "ENCO 1st Spread": ("WTI", "CALCULATE", "SPRD", 1, 1),
    "ENCO 2nd Spread": ("WTI", "CALCULATE", "SPRD", 1, 1),
    "ENCO 3rd Spread": ("WTI", "CALCULATE", "SPRD", 1, 1),
    "ENCO Dec-Dec Spread": ("WTI", "CALCULATE", "SPRD", 1, 1),
    "XOP US Equity": ("WTI", "COPY", "FLAT", 1, 1),
    "XLE US Equity": ("WTI", "COPY", "FLAT", 1, 1),
    "OSX Index": ("WTI", "COPY", "FLAT", 1, 0),
    "CVX US Equity": ("WTI", "COPY", "FLAT", 1, 1),
    "VLO US Equity": ("WTI", "COPY", "FLAT", 1, 1),
    "PBF US Equity": ("WTI", "COPY", "FLAT", 1, 1),
    "PAA US Equity": ("WTI", "COPY", "FLAT", 1, 1),
    "ENB CN Equity": ("WTI", "COPY", "FLAT", 1, 1),
    "QSA Comdty": ("DIST", "TICKER", "FLAT", 1, 1),
    "QS2 Comdty": ("DIST", "CONTRACT", "FLAT", 1, 1),
    "QS3 Comdty": ("DIST", "CONTRACT", "FLAT", 0, 1),
    "QS4 Comdty": ("DIST", "CONTRACT", "FLAT", 0, 1),
    "QS6 Comdty": ("DIST", "CONTRACT", "FLAT", 0, 1),
    "QSDEC1 Comdty": ("DIST", "FUT_CUR_GEN_TICKER", "FLAT", 1, 1),
    "QSDEC2 Comdty": ("DIST", "FUT_CUR_GEN_TICKER", "FLAT", 1, 1),
    "S:QSQS 2-6 Comdty": ("DIST", "CALSPRD", "SPRD", 1, 1),
    "QS 1st Spread": ("DIST", "CALCULATE", "SPRD", 1, 1),
    "QS 2nd Spread": ("DIST", "CALCULATE", "SPRD", 1, 1),
    "QS 3rd Spread": ("DIST", "CALCULATE", "SPRD", 1, 1),
    "QS Quarter Spread": ("DIST", "CALCULATE", "SPRD", 1, 1),
    "QS Dec-Dec Spread": ("DIST", "CALCULATE", "SPRD", 1, 1),
    "HOA Comdty": ("DIST", "TICKER", "FLAT", 1, 1),
    "HO2 Comdty": ("DIST", "CONTRACT", "FLAT", 1, 1),
    "HO3 Comdty": ("DIST", "CONTRACT", "FLAT", 0, 1),
    "HO4 Comdty": ("DIST", "CONTRACT", "FLAT", 0, 1),
    "HO6 Comdty": ("DIST", "CONTRACT", "FLAT", 0, 1),
    "HODEC1 Comdty": ("DIST", "FUT_CUR_GEN_TICKER", "FLAT", 1, 1),
    "HODEC2 Comdty": ("DIST", "FUT_CUR_GEN_TICKER", "FLAT", 1, 1),
    "S:HOHO 2-6 Comdty": ("DIST", "CALSPRD", "SPRD", 1, 1),
    "HO 1st Spread": ("DIST", "CALCULATE", "SPRD", 1, 1),
    "HO 2nd Spread": ("DIST", "CALCULATE", "SPRD", 1, 1),
    "HO 3rd Spread": ("DIST", "CALCULATE", "SPRD", 1, 1),
    "HO Quarter Spread": ("DIST", "CALCULATE", "SPRD", 1, 1),
    "HO Dec-Dec Spread": ("DIST", "CALCULATE", "SPRD", 1, 1),
    "HOCL 1st Spread": ("DIST", "CALCULATE", "SPRD", 1, 1),
    "HOCL 2nd Spread": ("DIST", "CALCULATE", "SPRD", 1, 1),
    "FVHRM 1st Spread": ("DIST", "COSPREAD", "SPRD", 1, 1),
    "FVHRM 6th Spread": ("DIST", "COSPREAD", "SPRD", 1, 1),
    "FVHRM 12th Spread": ("DIST", "COSPREAD", "SPRD", 1, 1),
    "XBA Comdty": ("GASOLINE", "TICKER", "FLAT", 1, 1),
    "XB2 Comdty": ("GASOLINE", "CONTRACT", "FLAT", 1, 1),
    "XB3 Comdty": ("GASOLINE", "CONTRACT", "FLAT", 0, 1),
    "XB4 Comdty": ("GASOLINE", "CONTRACT", "FLAT", 0, 1),
    "XB5 Comdty": ("GASOLINE", "CONTRACT", "FLAT", 0, 1),
    "XB6 Comdty": ("GASOLINE", "CONTRACT", "FLAT", 0, 1),
    "S:XBXB 2-6 Comdty": ("GASOLINE", "CALSPRD", "SPRD", 1, 1),
    "XB 1st Spread": ("GASOLINE", "CALCULATE", "SPRD", 1, 1),
    "XB 2nd Spread": ("GASOLINE", "CALCULATE", "SPRD", 1, 1),
    "XB 3rd Spread": ("GASOLINE", "CALCULATE", "SPRD", 1, 1),
    "XB 4th Spread": ("GASOLINE", "CALCULATE", "SPRD", 1, 1),
    "XB 5th Spread": ("GASOLINE", "CALCULATE", "SPRD", 1, 1),
    "XBCL 1st Spread": ("GASOLINE", "CALCULATE", "SPRD", 1, 1),
    "XBCL 2nd Spread": ("GASOLINE", "CALCULATE", "SPRD", 1, 1),
    "FVXRM 1st Spread": ("GASOLINE", "COSPREAD", "SPRD", 1, 1),
    "FVXRM 6th Spread": ("GASOLINE", "COSPREAD", "SPRD", 1, 1),
    "XBHO 1st Spread": ("GASOLINE", "CALCULATE", "SPRD", 1, 1),
    "XBHO 2nd Spread": ("GASOLINE", "CALCULATE", "SPRD", 1, 1),
    "XBHO 3rd Spread": ("GASOLINE", "CALCULATE", "SPRD", 1, 1),
    "IHWA Comdty": ("GASOLINE", "TICKER", "FLAT", 0, 1),
    "IHW2 Comdty": ("GASOLINE", "CONTRACT", "FLAT", 1, 1),
    "IHW3 Comdty": ("GASOLINE", "CONTRACT", "FLAT", 1, 1),
    "IHW4 Comdty": ("GASOLINE", "CONTRACT", "FLAT", 0, 1),
    "IHW 1st Spread": ("GASOLINE", "CALCULATE", "SPRD", 0, 1),
    "IHW 2nd Spread": ("GASOLINE", "CALCULATE", "SPRD", 1, 1),
    "IHW 3rd Spread": ("GASOLINE", "CALCULATE", "SPRD", 1, 1),
    "NGA Comdty": ("HH", "TICKER", "FLAT", 1, 1),
    "NG2 Comdty": ("HH", "CONTRACT", "FLAT", 1, 1),
    "NG3 Comdty": ("HH", "CONTRACT", "FLAT", 1, 1),
    "NG4 Comdty": ("HH", "CONTRACT", "FLAT", 1, 1),
    "NG5 Comdty": ("HH", "CONTRACT", "FLAT", 0, 1),
    "NG6 Comdty": ("HH", "CONTRACT", "FLAT", 0, 1),
    "S:NGNG 2-6 Comdty": ("HH", "CALSPRD", "SPRD", 1, 1),
    "NG 1st Spread": ("HH", "CALCULATE", "SPRD", 1, 1),
    "NG 2nd Spread": ("HH", "CALCULATE", "SPRD", 1, 1),
    "NG 3rd Spread": ("HH", "CALCULATE", "SPRD", 1, 1),
    "NGOCT1 Comdty": ("HH", "FUT_CUR_GEN_TICKER", "FLAT", 0, 1),
    "NG Oct-Jan Spread": ("HH", "CALCULATE", "SPRD", 1, 1),
    "NG 1M 100 VOL BVOL Comdty": ("HH", "COPY", "SPRD", 1, 0),
    ".NG1MRR Index": ("HH", "COPY", "SPRD", 1, 0),
    "FSNGY 23 Index": ("HH", "ROLLYEAR", "FLAT", 1, 0),
    "FSNGY 24 Index": ("HH", "ROLLYEAR+1", "FLAT", 1, 0),
    "FSNGY 25 Index": ("HH", "ROLLYEAR+2", "FLAT", 1, 0),
    "FSNGY 26 Index": ("HH", "ROLLYEAR+3", "FLAT", 1, 0),
    "FSNGS SU23 Index": ("HH", "ROLLYEAR", "FLAT", 1, 0),
    "FSNGS SU24 Index": ("HH", "ROLLYEAR+1", "FLAT", 1, 0),
    "FSNGS SU25 Index": ("HH", "ROLLYEAR+2", "FLAT", 1, 0),
    "FSNGS WI2223 Index": ("HH", "ROLLYEAR", "FLAT", 1, 0),
    "FSNGS WI2324 Index": ("HH", "ROLLYEAR+1", "FLAT", 1, 0),
    "FSNGS WI2425 Index": ("HH", "ROLLYEAR+2", "FLAT", 1, 0),
    "CTIA Comdty": ("HH", "TICKER", "FLAT", 1, 1),
    "XNG Index": ("HH", "COPY", "FLAT", 1, 0),
    "LNG US Equity": ("HH", "COPY", "FLAT", 1, 1),
    "VST US Equity": ("HH", "COPY", "FLAT", 1, 1),
    "TLNE US Equity": ("HH", "COPY", "FLAT", 1, 1),
    "CEG US Equity": ("HH", "COPY", "FLAT", 1, 1),
    "NRG US Equity": ("HH", "COPY", "FLAT", 1, 1),
    ".DRY_E&P Index": ("HH", "COPY", "FLAT", 1, 0),
    "FN3PM1 Index": ("HH", "COPY", "FLAT", 1, 0),
    "FN3PM2 Index": ("HH", "COPY", "FLAT", 1, 0),
    "FN3PM3 Index": ("HH", "COPY", "FLAT", 1, 0),
    "FN3PQ1 Index": ("HH", "COPY", "FLAT", 1, 0),
    "FN3PQ2 Index": ("HH", "COPY", "FLAT", 1, 0),
    "FN3PQ3 Index": ("HH", "COPY", "FLAT", 1, 0),
    "FN3PY1 Index": ("HH", "COPY", "FLAT", 1, 0),
    "FN3PY2 Index": ("HH", "COPY", "FLAT", 1, 0),
    "FN3PY3 Index": ("HH", "COPY", "FLAT", 1, 0),
    "FN3PY4 Index": ("HH", "COPY", "FLAT", 1, 0),
    "PJMF1MON Index": ("HH", "COPY", "FLAT", 1, 0),
    "PJMF2MON Index": ("HH", "COPY", "FLAT", 1, 0),
    "PJMF3MON Index": ("HH", "COPY", "FLAT", 1, 0),
    "PJMFQ1 Index": ("HH", "COPY", "FLAT", 1, 0),
    "PJMFQ2 Index": ("HH", "COPY", "FLAT", 1, 0),
    "PJMFQ3 Index": ("HH", "COPY", "FLAT", 1, 0),
    "PJMFY 24 Index": ("HH", "ROLLYEAR", "FLAT", 1, 0),
    "PJMFY 25 Index": ("HH", "ROLLYEAR+1", "FLAT", 1, 0),
    "PJMFY 26 Index": ("HH", "ROLLYEAR+2", "FLAT", 1, 0),
    "TZTA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "TZT2 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "TZT3 Comdty": ("TTF", "CONTRACT", "FLAT", 0, 1),
    "TZT4 Comdty": ("TTF", "CONTRACT", "FLAT", 0, 1),
    "TZT 1st spread": ("TTF", "CALCULATE", "SPRD", 1, 1),
    "TZT 2nd spread": ("TTF", "CALCULATE", "SPRD", 1, 1),
    "TZT 3rd spread": ("TTF", "CALCULATE", "SPRD", 1, 1),
    "QZTA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "QZT2 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "QZT3 Comdty": ("TTF", "CONTRACT", "FLAT", 0, 1),
    "QZT 1st spread": ("TTF", "CALCULATE", "SPRD", 1, 1),
    "QZT 2nd spread": ("TTF", "CALCULATE", "SPRD", 1, 1),
    "QQTA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "QQT2 Comdty": ("TTF", "CONTRACT", "FLAT", 0, 1),
    "QQT3 Comdty": ("TTF", "CONTRACT", "FLAT", 0, 1),
    "QQT 1st spread": ("TTF", "CALCULATE", "SPRD", 1, 1),
    "QQT 2nd spread": ("TTF", "CALCULATE", "SPRD", 1, 1),
    "QTTA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "QTT2 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "QTT3 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "QTT4 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "QTT 1st spread": ("TTF", "CALCULATE", "SPRD", 1, 1),
    "FJS 1M 100 VOL BVOL Comdty": ("TTF", "COPY", "SPRD", 1, 0),
    ".FJS1MRR Index": ("TTF", "COPY", "SPRD", 1, 0),
    "MOA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "XAA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "XEA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "TMA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "EQNR NO Equity": ("TTF", "COPY", "FLAT", 1, 1),
    "GERW1WYY Comdty": ("TTF", "WEEKLY", "FLAT", 1, 1),
    "GERW2WYY Comdty": ("TTF", "WEEKLY", "FLAT", 1, 1),
    "DETA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "DET2 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "JXTA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "JXT2 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "JXT 1st spread": ("TTF", "CALCULATE", "SPRD", 1, 1),
    "JXYA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "JXY2 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "JXY3 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "JXY 1st spread": ("TTF", "CALCULATE", "SPRD", 1, 1),
    "ELFBDAHD Index": ("TTF", "COPY", "FLAT", 1, 0),
    "FIB2W Comdty": ("TTF", "COPY", "FLAT", 1, 0),
    "FIB3W Comdty": ("TTF", "COPY", "FLAT", 1, 0),
    "FACA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "FAC2 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "FAC3 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "FABA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "FAB2 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "FAB3 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "FAB4 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "FAAA Comdty": ("TTF", "TICKER", "FLAT", 1, 1),
    "FAA2 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "FAA3 Comdty": ("TTF", "CONTRACT", "FLAT", 1, 1),
    "HGA Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    "HG2 Comdty": ("BM", "CONTRACT", "FLAT", 0, 1),
    "HG3 Comdty": ("BM", "CONTRACT", "FLAT", 0, 1),
    "HG 1st Spread": ("BM", "CALCULATE", "SPRD", 1, 1),
    "HG 2nd Spread": ("BM", "CALCULATE", "SPRD", 1, 1),
    "LMCADS03 Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    "LMAHDS03 Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    "LMNIDS03 Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    "LMZSDS03 Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    "LMSNDS03 Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    "LMPBDS03 Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    "LMCADS Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    "LMAHDS Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    "LMZSDS Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    "LMNIDS Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    "LMCADS 03Z25 Comdty": ("BM", "COPY", "SPRD", 1, 1),
    "LMCADS Z25Z26 Comdty": ("BM", "COPY", "SPRD", 1, 1),
    "LMCADS 1st Spread": ("BM", "LMESPREAD", "SPRD", 1, 1),
    "LMCADS 2nd Spread": ("BM", "LMESPREAD", "SPRD", 1, 1),
    "LMCADS 3rd Spread": ("BM", "LMESPREAD", "SPRD", 1, 1),
    "LMAHDS 03Z25 Comdty": ("BM", "COPY", "SPRD", 1, 1),
    "LMAHDS Z25Z26 Comdty": ("BM", "COPY", "SPRD", 1, 1),
    "LMAHDS 1st Spread": ("BM", "LMESPREAD", "SPRD", 1, 1),
    "LMAHDS 2nd Spread": ("BM", "LMESPREAD", "SPRD", 1, 1),
    "LMAHDS 3rd Spread": ("BM", "LMESPREAD", "SPRD", 1, 1),
    "LMZSDS 03Z25 Comdty": ("BM", "COPY", "SPRD", 1, 1),
    "LMZSDS Z25Z26 Comdty": ("BM", "COPY", "SPRD", 1, 1),
    "LMZSDS 1st Spread": ("BM", "LMESPREAD", "SPRD", 1, 1),
    "LMZSDS 2nd Spread": ("BM", "LMESPREAD", "SPRD", 1, 1),
    "LMZSDS 3rd Spread": ("BM", "LMESPREAD", "SPRD", 1, 1),
    "LMNIDS 03Z25 Comdty": ("BM", "COPY", "SPRD", 1, 1),
    "LMNIDS Z25Z26 Comdty": ("BM", "COPY", "SPRD", 1, 1),
    "LMNIDS 1st Spread": ("BM", "LMESPREAD", "SPRD", 1, 1),
    "LMNIDS 2nd Spread": ("BM", "LMESPREAD", "SPRD", 1, 1),
    "LMNIDS 3rd Spread": ("BM", "LMESPREAD", "SPRD", 1, 1),
    "CUA Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    ".CUCH12US Index": ("BM", "COPY", "SPRD", 1, 0),
    ".CUCH23US Index": ("BM", "COPY", "SPRD", 1, 0),
    ".CUCH34US Index": ("BM", "COPY", "SPRD", 1, 0),
    "CU 1st Spread": ("BM", "CALCULATE", "SPRD", 1, 1),
    "CU 2nd Spread": ("BM", "CALCULATE", "SPRD", 1, 1),
    "CECN00CU Index": ("BM", "COPY", "SPRD", 1, 0),
    "LPARB": ("BM", "CUSTOM", "SPRD", 1, 0),
    "AAA Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    ".CHAL12US Index": ("BM", "COPY", "SPRD", 1, 0),
    ".CHAL23US Index": ("BM", "COPY", "SPRD", 1, 0),
    ".CHAL34US Index": ("BM", "COPY", "SPRD", 1, 0),
    "AA 1st Spread": ("BM", "CALCULATE", "SPRD", 1, 1),
    "AA 2nd Spread": ("BM", "CALCULATE", "SPRD", 1, 1),
    "LAARB": ("BM", "CUSTOM", "SPRD", 1, 0),
    "XIIA Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    ".CHNI12 Index": ("BM", "COPY", "SPRD", 1, 0),
    ".CHNI23 Index": ("BM", "COPY", "SPRD", 1, 0),
    ".CHNI34 Index": ("BM", "COPY", "SPRD", 1, 0),
    "XII 1st Spread": ("BM", "CALCULATE", "SPRD", 1, 1),
    "XII 2nd Spread": ("BM", "CALCULATE", "SPRD", 1, 1),
    "ZNAA Comdty": ("BM", "TICKER", "FLAT", 1, 1),
    ".CHZN12US Index": ("BM", "COPY", "SPRD", 1, 0),
    ".CHZN23US Index": ("BM", "COPY", "SPRD", 1, 0),
    ".CHZN34US Index": ("BM", "COPY", "SPRD", 1, 0),
    "ZNA 1st Spread": ("BM", "CALCULATE", "SPRD", 1, 1),
    "ZNA 2nd Spread": ("BM", "CALCULATE", "SPRD", 1, 1),
    "LXARB": ("BM", "CUSTOM", "SPRD", 1, 0),
    "LLARB": ("BM", "CUSTOM", "SPRD", 1, 0),
    "SXPP Index": ("BM", "COPY", "FLAT", 1, 0),
    "XME US Equity": ("BM", "COPY", "FLAT", 1, 1),
    "GLEN LN Equity": ("BM", "COPY", "FLAT", 1, 0),
    "AA US Equity": ("BM", "COPY", "FLAT", 1, 0),
    "NUE US Equity": ("BM", "COPY", "FLAT", 1, 0),
    "BHP LN Equity": ("BM", "COPY", "FLAT", 1, 0),
    "SH000909 Index": ("BM", "COPY", "FLAT", 1, 0),
    "COPX US Equity": ("BM", "COPY", "FLAT", 1, 0),
    "IOEA Comdty": ("Bulks", "TICKER", "FLAT", 1, 1),
    "RBTA Comdty": ("Bulks", "TICKER", "FLAT", 1, 1),
    "SCOA Comdty": ("Bulks", "TICKER", "FLAT", 1, 1),
    "C A Comdty": ("GR", "TICKER", "FLAT", 1, 1),
    "C 2 Comdty": ("GR", "CONTRACT", "FLAT", 1, 1),
    "C 3 Comdty": ("GR", "CONTRACT", "FLAT", 0, 1),
    "C DEC1 Comdty": ("GR", "FUT_CUR_GEN_TICKER", "FLAT", 0, 1),
    "C DEC2 Comdty": ("GR", "FUT_CUR_GEN_TICKER", "FLAT", 0, 1),
    "C  1st Spread": ("GR", "CALCULATE", "SPRD", 1, 1),
    "C  2nd Spread": ("GR", "CALCULATE", "SPRD", 1, 1),
    "C  Dec-Dec Spread": ("GR", "CALCULATE", "SPRD", 1, 1),
    "S A Comdty": ("GR", "TICKER", "FLAT", 1, 1),
    "S 2 Comdty": ("GR", "CONTRACT", "FLAT", 1, 1),
    "S 3 Comdty": ("GR", "CONTRACT", "FLAT", 0, 1),
    "S NOV1 Comdty": ("GR", "FUT_CUR_GEN_TICKER", "FLAT", 0, 1),
    "S NOV2 Comdty": ("GR", "FUT_CUR_GEN_TICKER", "FLAT", 0, 1),
    "S  1st Spread": ("GR", "CALCULATE", "SPRD", 1, 1),
    "S  2nd Spread": ("GR", "CALCULATE", "SPRD", 1, 1),
    "S  Nov-Nov Spread": ("GR", "CALCULATE", "SPRD", 1, 1),
    "W A Comdty": ("GR", "TICKER", "FLAT", 1, 1),
    "W 2 Comdty": ("GR", "CONTRACT", "FLAT", 1, 1),
    "W 3 Comdty": ("GR", "CONTRACT", "FLAT", 0, 1),
    "W DEC1 Comdty": ("GR", "FUT_CUR_GEN_TICKER", "FLAT", 0, 1),
    "W DEC2 Comdty": ("GR", "FUT_CUR_GEN_TICKER", "FLAT", 0, 1),
    "W  1st Spread": ("GR", "CALCULATE", "SPRD", 1, 1),
    "W  2nd Spread": ("GR", "CALCULATE", "SPRD", 1, 1),
    "W  Dec-Dec Spread": ("GR", "CALCULATE", "SPRD", 1, 1),
    "SMA Comdty": ("GR", "TICKER", "FLAT", 1, 1),
    "SM2 Comdty": ("GR", "CONTRACT", "FLAT", 0, 1),
    "SM 1st Spread": ("GR", "CALCULATE", "SPRD", 1, 1),
    "BOA Comdty": ("GR", "TICKER", "FLAT", 1, 1),
    "BO2 Comdty": ("GR", "CONTRACT", "FLAT", 0, 1),
    "BO 1st Spread": ("GR", "CALCULATE", "SPRD", 1, 1),
    ".SOYCORN Index": ("GR", "COPY", "SPRD", 1, 0),
    ".WCORN Index": ("GR", "COPY", "SPRD", 1, 0),
    ".SOYWHEAT Index": ("GR", "COPY", "SPRD", 1, 0),
    "KWA Comdty": ("GR", "TICKER", "FLAT", 1, 1),
    "CAA Comdty": ("GR", "TICKER", "FLAT", 1, 1),
    "AKA Comdty": ("GR", "TICKER", "FLAT", 1, 1),
    "AEA Comdty": ("GR", "TICKER", "FLAT", 1, 1),
    "ACA Comdty": ("GR", "TICKER", "FLAT", 1, 1),
    "SBA Comdty": ("SFT", "TICKER", "FLAT", 1, 1),
    "SB2 Comdty": ("SFT", "CONTRACT", "FLAT", 1, 1),
    "SB3 Comdty": ("SFT", "CONTRACT", "FLAT", 0, 1),
    "SB4 Comdty": ("SFT", "CONTRACT", "FLAT", 0, 1),
    "SB 1st Spread": ("SFT", "CALCULATE", "SPRD", 1, 1),
    "SB 2nd Spread": ("SFT", "CALCULATE", "SPRD", 1, 1),
    "QWA Comdty": ("SFT", "TICKER", "FLAT", 1, 1),
    "QW2 Comdty": ("SFT", "CONTRACT", "FLAT", 1, 1),
    "QW 1st Spread": ("SFT", "CALCULATE", "SPRD", 1, 1),
    ".QWOCT S 92051579 Index": ("SFT", "COPY", "SPRD", 1, 0),
    "CCA Comdty": ("SFT", "TICKER", "FLAT", 1, 1),
    "CC2 Comdty": ("SFT", "CONTRACT", "FLAT", 0, 1),
    "CC 1st Spread": ("SFT", "CALCULATE", "SPRD", 1, 1),
    "QCA Comdty": ("SFT", "TICKER", "FLAT", 1, 1),
    "QC2 Comdty": ("SFT", "CONTRACT", "FLAT", 0, 1),
    "QC 1st Spread": ("SFT", "CALCULATE", "SPRD", 1, 1),
    "KCA Comdty": ("SFT", "TICKER", "FLAT", 1, 1),
    "KC2 Comdty": ("SFT", "CONTRACT", "FLAT", 0, 1),
    "KC 1st Spread": ("SFT", "CALCULATE", "SPRD", 1, 1),
}

month_ticker_dict = {
    "JAN": "F",
    "FEB": "G",
    "MAR": "H",
    "APR": "J",
    "MAY": "K",
    "JUN": "M",
    "JUL": "N",
    "AUG": "Q",
    "SEP": "U",
    "OCT": "V",
    "NOV": "X",
    "DEC": "Z",
}

month_ticker_dict1 = {
    1: "F",
    2: "G",
    3: "H",
    4: "J",
    5: "K",
    6: "M",
    7: "N",
    8: "Q",
    9: "U",
    10: "V",
    11: "X",
    12: "Z",
}

diverg_list = [
    ("CO 1st Spread", "COA Comdty"),
    ("S:COCO 2-6 Comdty", "CO2 Comdty"),
    ("CL 1st Spread", "CLA Comdty"),
    ("S:CLCL 2-6 Comdty", "CL2 Comdty"),
    ("XB 1st Spread", "XBA Comdty"),
    ("S:XBXB 2-6 Comdty", "XB2 Comdty"),
    ("HO 1st Spread", "HOA Comdty"),
    ("S:HOHO 2-6 Comdty", "HO2 Comdty"),
    ("NG 1st Spread", "NGA Comdty"),
    ("S:NGNG 2-6 Comdty", "NG2 Comdty"),
    ("TZT 1st spread", "TZTA Comdty"),
    ("JKM/TTF", "TZTA Comdty"),
]

option_dict = {
    "Brent": ["COA Comdty"],
    "WTI": ["CLA Comdty", "ENA Comdty"],
    "NG": ["GKA Comdty"],
    "TTF": ["TZTA Comdty", "FJSA Comdty"],
    "EUA": ["MZBA Comdty"],
    "LME Copper": ["LPA Comdty"],
    "Gold": ["GCA Comdty"],
    "Silver": ["SIA Comdty"],
    "Corn": ["C A Comdty"],
    "Wheat": ["W A Comdty"],
    "Soybean": ["S A Comdty"],
    "SoyOil": ["BOA Comdty"],
    "SoyMeal": ["SMA Comdty"],
    "Sugar": ["SBA Comdty"],
    "Cotton": ["CTA Comdty"],
}

spots_dict = {
    "Forties": ["PCRUFRT2 Index", "AAGWZ00", "NWE Crude", "CO 2nd Spread", True],
    "Eko": ["PCRUEKO2 PLDP Index", "AAGXB00", "NWE Crude", "CO 2nd Spread", True],
    "Urals": ["PCRUURD1 PLDP Index", "AAGXJ00", "NWE Crude", "CO 2nd Spread", True],
    "CPC": ["PCRUTENG PLDP Index", "AAHPL00", "NWE Crude", "CO 2nd Spread", True],
    "Saharan": ["PCRUSHBA PLDP Index", "AAHPN00", "NWE Crude", "CO 2nd Spread", True],
    "Azeri": ["PCRUAZCF PLDP Index", "AAHPM00", "NWE Crude", "CO 2nd Spread", True],
    "WTI Dlvd": ["NARI00EF PLDP Index", "WMCRB00", "NWE Crude", "CO 2nd Spread", True],
    "Brent": ["PCRUBNBD PLDP Index", "AAVJB00", "NWE Crude", "CO 2nd Spread", True],
    "Cash Midland": ["USCSWTIM Index", None, "US Crude", "CL 2nd Spread", True],
    "Paper Midland": ["FFA1 Comdty", None, "US Crude", "CL 2nd Spread", True],
    "Cash MEH": ["NARU000E PLDP Index", "AAYRH00", "US Crude", "CL 2nd Spread", True],
    "paper MEH": ["HRT1 Comdty", None, "US Crude", "CL 2nd Spread", True],
    "Mars": ["USCSMARS Index", None, "US Crude", "CL 2nd Spread", True],
    "WCS Ned": ["NARU001E PLDP Index", "AAYAX00", "US Crude", "CL 2nd Spread", True],
    "WCS Cush": ["PCUC1002 PLDP Index", "AAWTZ00", "US Crude", "CL 2nd Spread", True],
    "WTI USGC FOB": ["NARU0022 PLDP Index", "AAYAZ00", "US Crude", "CL 2nd Spread", True],
    "BLS Link": ["BKCUM1 LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "Bakken USGC Link": ["BKGCM1 LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "Nio Link": ["NBCCM1 LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "MEH Link": ["WMEHSPOT LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "Middy Link": ["PWTMSPOT LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "DJ WhiteCliffs Link": ["WCCDM1 LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "WTI Cash Link": ["LNKSCASH LINK Index", None, "US Crude", "CL 1st Spread", True],
    "WTI Ex-Basin Link": ["LNKSWTXB LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "WTI Midland Link": ["LNKSMDSW LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "WTI MEH Link": ["LNKSMEHS LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "WTI Bakken Link": ["LNKSBGUL LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "WTI Corpus Link": ["LNKSWTCC LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "Bakken Light Link": ["LNKSBCUS LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "Niobrara Link": ["LNKSNIOB LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "Bakken": ["BKCUSPOT LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "Saddlehorn Link": ["PSHLBOM LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "White Cliffs Link": ["LNKSWCLF LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "Mars Link": ["LNKSMARS LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "WCS Link": ["LNKSWCSG LINK Index", None, "US Crude", "CL 2nd Spread", True],
    "Bonny": ["PCRUBLT2 PLDP Index", "AAGXL00", "WAF Crude", "CO 2nd Spread", True],
    "Forcs": ["PCRUFOR2 PLDP Index", "AAGXP00", "WAF Crude", "CO 2nd Spread", True],
    "Egina": ["NARI0114 PLDP Index", "AFONB00", "WAF Crude", "CO 2nd Spread", True],
    "Hungo": ["PCRUHUNG PLDP Index", "AASJF00", "WAF Crude", "CO 2nd Spread", True],
    "Dalia": ["PCRU1145 PLDP Index", "AAQYY00", "WAF Crude", "CO 2nd Spread", True],
    "TC5": ["WMJ", None, "Clean Freight", "QS 2nd Spread", True],
    "TC2": ["WNU", None, "Clean Freight", "QS 2nd Spread", True],
    "TD3C": ["OYA Comdty", None, "Dirty Freight", "CO 2nd Spread", True],
    "TD22": ["WF2", None, "Dirty Freight", "CO 2nd Spread", True],
    "TD25": ["WF5", None, "Dirty Freight", "CO 2nd Spread", True],
    "USGC Gasoline": ["NAUG006C PLDP Index", "AANYX79", "US Gasoline", "XB 2nd Spread", True],
    "Group 3 Gasoline": ["NAUG00AE PLDP Index", "AANYX02", "US Gasoline", "XB 2nd Spread", True],
    "NYH Gasoline": ["NAPN005C PLDP Index", "AANYX15", "US Gasoline", "XB 2nd Spread", True],
    "ULSD_Pipe": ["NAUG0074 PLDP Index", "ADIQA00", "US Dist", "HO 2nd Spread", True],
    "Group 3 disty": ["NAPI0006 Index", "ADLAB00", "US Dist", "HO 2nd Spread", True],
    "NYH ULSD Barges": ["NAPN006E PLDP Index", "ADIZA00", "US Dist", "HO 2nd Spread", True],
    "AlShaheen": ["PCRUAHDS Index", "AAPEW00", "Asia Crude", "DAT 2nd Spread", True],
    "Murban Dub": ["NARP0049 PLDP Index", "AARBZ00", "Asia Crude", "DAT 2nd Spread", True],
    "Sokol": ["PCRUSCDO PLDP Index", "AASCK00", "Asia Crude", "DAT 2nd Spread", True],
    "Tupi DES Qingdao": ["NARP0059 PLDP Index", "LUQDD00", "Asia Crude", "DAT 2nd Spread", True],
    "WTI DES Singapore": ["NARP005F PLDP Index", "WTMSD00", "Asia Crude", "DAT 2nd Spread", True],
    "Sing_gasoil": ["PASOGOSM PLDP Index", "POAIC00", "Sing Gasoil", "QS 2nd Spread", True],
    "MOPJ Naphtha": ["PASONMOP PLDP Index", "PAADI00", "Sing Naphtha", "XB 2nd Spread", True],
    "0.5 Marine": ["NACX0011 Index", "FOFSB00", "Sing VLSFO", "QS 2nd Spread", True],
    "380 FO": ["PASOVMFO Index", "PPXDL00", "Sing HSFO", None, True],
    "Jet": ["PASOJKSM PLDP Index", "PJACU00", "Sing Jet", "QS 2nd Spread", True],
    "CFD 1wk": ["PCRUBCD1 PLRT Index", "PCAKA00", "NWE Crude", "CO 2nd Spread", True],
    "CFD 2wk": ["PCRUBCD2 PLRT Index", "PCAKC00", "NWE Crude", "CO 2nd Spread", True],
    "CFD 3wk": ["PCRUBCD3 PLRT Index", "PCAKE00", "NWE Crude", "CO 2nd Spread", True],
    "CFD 4wk": ["PCRUBCD4 PLRT Index", "PCAKG00", "NWE Crude", "CO 2nd Spread", True],
    "CFD 5wk": ["PCRUBCD5 PLRT Index", "AAGLU00", "NWE Crude", "CO 2nd Spread", True],
    "CFD 6wk": ["PCRUBCD6 PLRT Index", "AAGLV00", "NWE Crude", "CO 2nd Spread", True],
    "CFD 7wk": ["PCRUBCD7 PLRT Index", "AALCZ00", "NWE Crude", "CO 2nd Spread", True],
    "CFD 8wk": ["PCRUBCD8 PLRT Index", "AALDA00", "NWE Crude", "CO 2nd Spread", True],
}

other_platts_dict = {
    "VGO 0.5-0.6%": ["INFSVGOC Index", "AAHMX00"],
    "VGO 2%": ["INFSVGOD Index", "AAHNB00"],
    "Reformate": ["PLFUFS12 Index", "AAXBC00"],
    "Reformate diff": ["", "AAJMV00"],
    "Alkylate": ["PLFUFS10 Index", "AAXBA00"],
    "Alkylata diff": ["PUSPGCAB Index", "AAFIE00"],
    "Line space": ["NAUG004B Index", "AAXTD00"],
    "Johan Sverdrup": ["NARI0118 Index", "AJSVB00"],
    "Barge FP": ["PEURGONW Index", "AAJUS00"],
    "CIF N.WE": ["PEURBG00 PLDP Index", "AAVBG00"],
    "MED CIF": ["PEURM10C Index", "AAWYZ00"],
    "50ppm": ["PEURG50B PLDP Index", "AAUQC00"],
    "Jet": ["PEURJKCC Index", "PJAAU00"],
    "0.1 Barge": ["PEURG1FA PLDP Index", "AAYWT00"],
    "NYH Jet diff": ["NAPN006A PLDP Index", "ADIGA00"],
    "Sing Jet": ["PASOJKSG PLDP Index", "PJABF00"],
    "10ppm Gasoil": ["PASOG10S PLDP Index", "AAOVC00"],
    "MOPAG": ["LHAG0006 PLDP Index", "AAIDU00"],
    "WCI": ["PASO1004 Index", "AAQWN00"],
    "EBOB barges": ["PEUREBOB PLDP Index", "AAQZV00"],
    "E10": ["LHEB001B PLDP Index", "AGEFA00"],
    "EU MED CIF": ["PEURF10M Index", "AAWZA00"],
    "Nap": ["PEURNPHY PLDP Index", "PAAAL00"],
    "Cycle 2": ["PUSPRGBP PLDP Index", "AAELD00"],
    "Cycle 3": ["PUSPNFGU PLDP Index", "AAELE00"],
    "Linden": ["NAPN005F PLDP Index", "AANYX40"],
    "Sing gasoline": ["PASORONM Index", "AAXER00"],
    "92 ron": ["PASOMG92 PLDP Index", "PGAEY00"],
    "95 ron": ["PASOMGCS PLDP Index", "PGAEZ00"],
    "Platts WTI delivered": ["NARI0125 Index", "WMCRB00"],
    "Oman": ["NARP0073 Index", "DBDOC00"],
    "Upper Zakum": ["NARP0077 Index", "DBDUZ00"],
    "Mars": ["PCUCMRD1 Index", "AAGWH00"],
    "WTI FOB": ["NARI0148 PLDP Index", "ALNDB00"],
}
