repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff
        args:
          - --fix
          - --extend-select=I
      - id: ruff-format
        args:
          - --line-length=120
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
      - id: mypy
        name: mypy
        files: \.pyi?$
        exclude: ^(\.gitignore|README\.md|pixi\.lock|data/|var/|\.pixi/|packages/.*/LICENSE)$
        args:
          - --python-version=3.11
          - --ignore-missing-imports
          - --namespace-packages
          - --explicit-package-bases
